#!/bin/bash

g++ -o heap.o src/heapSort.cpp;

mkdir testOutput/heap;

echo input 1;
./heap.o < inputs/1.txt > testOutput/heap/Output1.txt;
tail -1 testOutput/heap/Output1.txt

echo input 2;
./heap.o < inputs/2.txt > testOutput/heap/Output2.txt;
tail -1 testOutput/heap/Output2.txt

echo input 3;
./heap.o < inputs/3.txt > testOutput/heap/Output3.txt;
tail -1 testOutput/heap/Output3.txt

echo intput 4;
./heap.o < inputs/4.txt > testOutput/heap/Output4.txt;
tail -1 testOutput/heap/Output4.txt
